favicon:
  mimetype: image/vnd.microsoft.icon
  path: 'public://helmet_0.ico'
  url: /sites/default/files/helmet_0.ico
  use_default: false
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: 'public://football_50x50.png'
  url: ''
  use_default: false
schemas:
  bootstrap: 8000
  background: 8000
